# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec33c259c9be5fcb89ce59d40db256fc3efc234022a548b9e6a5eba1c0f81279fe1c3e52fc1002f9256a38a82ba5da778dffeb4a86c3959c66cde57deb0448f7

test:
  secret_key_base: 0d0f6516675f0aa358c5b769038d54c6654d507af2b81c441752cc5441b98f6b45a2acde97a9c7f78d17dbb60739a7f6a4a91fb48d2e28944fef893dcb5c51f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
